### ISSUE TITLE
Unable to download and attach PDF of SOME Dashboards

### ISSUE THREAD

**Issue by dantectl** [newrelic/nr-reports#9]
## Description
I can't find a specific pattern to why this happens, but some Dashboards can be downloaded via the CLI while others cannot. This applies across the board to multi-page Dashboards, but also to some single page Dashboards. 

## Error Message

```
./nr-reports-cli/bin/nr-reports.sh --debug -d <DASH_GUID>
[Mon, 12 Dec 2022 20:51:37 GMT] engine Created temporary directory dashboards-xJsCa4
[Mon, 12 Dec 2022 20:51:37 GMT] nerdgraph {"query":"mutation($guid: EntityGuid!){\n      dashboardCreateSnapshotUrl(guid: $guid)\n    }","variables":{"guid":"<DASH_GUID>"}}
[Mon, 12 Dec 2022 20:51:38 GMT] nerdgraph {"data":{"dashboardCreateSnapshotUrl":null},"errors":[{"extensions":{"errorClass":"SERVER_ERROR","type":"UNSUPPORTED_OPERATION"},"locations":[{"column":7,"line":2}],"message":"Unsupported operation on dashboard with given guid: <DASH_GUID>","path":["dashboardCreateSnapshotUrl"]}]}
[Mon, 12 Dec 2022 20:51:38 GMT] nerdgraph GraphQL post error for query: {"data":{"dashboardCreateSnapshotUrl":null},"errors":[{"extensions":{"errorClass":"SERVER_ERROR","type":"UNSUPPORTED_OPERATION"},"locations":[{"column":7,"line":2}],"message":"Unsupported operation on dashboard with given guid: <DASH_GUID>","path":["dashboardCreateSnapshotUrl"]}]}
[Mon, 12 Dec 2022 20:51:38 GMT] engine {}
Error: GraphQL post error for query: {"data":{"dashboardCreateSnapshotUrl":null},"errors":[{"extensions":{"errorClass":"SERVER_ERROR","type":"UNSUPPORTED_OPERATION"},"locations":[{"column":7,"line":2}],"message":"Unsupported operation on dashboard with given guid: <DASH_GUID>","path":["dashboardCreateSnapshotUrl"]}]}
    at NerdgraphClient.post (~/nr-reports/nr-reports-core/lib/nerdgraph.js:115:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async NerdgraphClient.query (~/nr-reports/nr-reports-core/lib/nerdgraph.js:145:25)
    at async downloadDashboardPdf (~/nr-reports/nr-reports-core/lib/engine.js:104:15)
    at async ~/nr-reports/nr-reports-core/lib/engine.js:268:11
    at async Promise.all (index 0)
    at async Engine.runDashboardReport (~/nr-reports/nr-reports-core/lib/engine.js:270:25)
    at async main (~/nr-reports/nr-reports-cli/index.js:142:9)
[Mon, 12 Dec 2022 20:51:38 GMT] engine Removing temporary directory dashboards-xJsCa4...

```

**Comment by sdewitt-newrelic** [comment]
@dantectl can you try to recreate on the latest v3.0.0 release?  Multi-page dashboards are not supported at this time.  If it is a single page dashboard, please share an example.

**Comment by sdewitt-newrelic** [comment]
Closing this because it is stale.  @dantectl create a new issue if it still occurs.
